name: Release

on:
  push:
    branches:
      - andras-patches

jobs:
  build-and-create-release:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      REPOSITORY: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: make build build-analyzer

      - name: Get current date and time
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d--%H-%M')" >> "$GITHUB_ENV"

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ env.date }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          name: "v${{ env.date }}"
          tag_name: "v${{ env.date }}"
          token: "${{ secrets.TOKEN_FOR_RELEASE }}"
          files: |
            LICENSE
            biogenesis.jar
            biogenesis-analyzer.jar
