name: Release

on:
  push:
    branches:
      - andras-patches
      - localized-gases

jobs:
  build-and-create-release:
    permissions:
      contents: write # allows the action to create a release
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      REPOSITORY: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Get current date and time
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d--%H-%M')" >> "$GITHUB_ENV"

      - name: Set version
        run: |
          echo "package biogenesis;" > src/biogenesis/Version.java
          echo "public interface Version {" >> src/biogenesis/Version.java
          echo "	public static final String VERSION = \"v${{ env.date }}\";" >> src/biogenesis/Version.java
          echo "}" >> src/biogenesis/Version.java

      - run: make build build-analyzer

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v${{ env.date }}"
          git tag
          git push origin "v${{ env.date }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          name: "v${{ env.date }}"
          tag_name: "v${{ env.date }}"
          files: |
            LICENSE
            biogenesis.jar
            biogenesis-analyzer.jar
